.TH "tcnetstat" "8" "" "" ""
.SH NAME
.PP
\f[B]tcnetstat\f[] \- Print information about network connections
protected by tcpcrypt
.SH SYNOPSIS
.PP
\f[B]tcnetstat\f[]
.SH DESCRIPTION
.PP
The \f[B]tcnetstat\f[] utility prints the \f[I]session id\f[] of each
TCP connection that is currently being managed by \f[B]tcpcryptd\f[](8).
.SH SEE ALSO
.PP
\f[B]tcpcryptd\f[](8), <http://tcpcrypt.org/>
